services:
  db:
    image: postgres:15-alpine
    container_name: azuredrop_db
    environment:
      - POSTGRES_USER=azuredrop_user
      - POSTGRES_PASSWORD=azuredrop_password
      - POSTGRES_DB=azuredrop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U azuredrop_user -d azuredrop_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: azuredrop_api
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=azuredrop_user
      - DB_PASSWORD=azuredrop_password
      - DB_NAME=azuredrop_db
      - UPLOAD_MODE=aws
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=louddrop-files-9912
  web:
    image: nginx:alpine
    container_name: azuredrop_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - api

volumes:
  postgres_data: